# Generated by Django 2.2.2 on 2019-06-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190618_1534'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='event',
            index_together={('id', 'slug')},
        ),
    ]
